### ISSUE TITLE
Update to opencv 2.4 beta

### ISSUE THREAD

**Issue by sradu** [aptogo/OpenCVForiPhone#4]
Hi!

Could you please update the repository to support opencv 2.4 beta?

-R.

**Comment by sradu** [comment]
2.4 beta doesn't build because of this:
http://code.opencv.org/issues/1626

**Comment by fonkadelic** [comment]
Building works for me with CMake 2.8.8 and Xcode 4.3. Used OpenCV 2.4.0 (r8149).

**Comment by sradu** [comment]
You're right. I had to upgrade cmake. Sorry for the issue.
